### ISSUE TITLE
Segfault linking llvm-sys

### ISSUE THREAD

**Issue by SUPERCILEX** [rui314/mold#1174]
Possibly related: https://github.com/rui314/mold/issues/1164

Create a `~/.cargo/config.toml` file and put this in it:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
  # Doubt these matter
  "-C", "target-cpu=native",
  "-C", "target-feature=-avx2",
  # This is the line that breaks things
  "-C", "link-arg=-fuse-ld=mold", "-C", "link-arg=-Wl,--icf=all",
]
```

Checkout https://github.com/TheDan64/inkwell/commit/0b2cde9394320ab6f097ef10408d663a28d44be3 and then run `cargo t --features llvm16-0`. Tasty segfault.
