### ISSUE TITLE
is macos supported?

### ISSUE THREAD

**Issue by shekohex** [rui314/mold#132]
Hello! This is an awesome project, I've been using it for a while now on my Linux machine before I switch to a macOS one lately and I was so happy to see some commit messages includes mesh-o and I wanted to ask if macOS support is being added?

I cloned the project locally and build it, and did a `sudo make install` and so far so good, but when I started to use it with my Rust project as I would normally using `mold -run cargo build --release` I get the following error:

```
mold: readlink("/proc/self/exe") failed: No such file or directory
```

So, I tried the other way using a `.cargo/config.toml`

```toml
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold", "-Zshare-generics=y"]
```

But then I get this error:
```
= note: mold: mold: unknown command line option: -dynamic
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

my OS information:

```
macOS BigSur 11.6.1 20G224 x86_64
```

Any idea? Thank you!
