### ISSUE TITLE
Rust program can't get command line args when linked with mold

### ISSUE THREAD

**Issue by Aloxaf** [rui314/mold#32]
Hello, this project is cool and I try to use it with Rust. But met a problem.

**Code**

```rust
fn main() {
    let me = std::env::args().next();
    println!("{:?}", me);
}
```

Run it with `cargo run`

**Expected result**

```
Some(PATH_OF_EXECUTABLE)
```

**Actually**

```
None
```

**Cargo config**

```toml
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=/usr/bin/mold"
]
```

Document of rust `std::env::args`: https://doc.rust-lang.org/std/env/fn.args.html
