### ISSUE TITLE
Mold causes Rust to lose backtraces in certain cases.

### ISSUE THREAD

**Issue by itsfarseen** [rui314/mold#33]
Minimal repro:
https://github.com/itsfarseen/repro-sqlx-rocket-anyhow-no-backtrace

A notable thing is, if I comment out `use sqlx;` import, it works fine. If I don't import `sqlx`, I think Rust compiler is smart enough to skip compiling it. 
I don't have to use anything inside sqlx, just importing it causes backtraces to be lost.

Cargo.toml
```toml
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
# rustflags = ["-Clink-arg=-fuse-ld=lld"]
rustflags = ["-Clink-arg=-fuse-ld=/usr/local/bin/mold"]
```

Rust version: rustc 1.53.0-nightly (ca075d268 2021-04-28)
