### ISSUE TITLE
mold miscompiles cargo-nextest

### ISSUE THREAD

**Issue by msfjarvis** [rui314/mold#347]
Building [nextest](https://github.com/nextest-rs/nextest) with `cargo install --locked cargo-nextest` generates an executable that stalls when run.

Running `strace cargo nextest run` to locate the source of this problem showed that the last syscall made by the program was `getrandom` after which it was doing nothing.

Cargo config

```toml
[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=mold", # Commenting this out generates executables that run correctly
]
```

Mold and Rust versions

```
➜ cargo --version
cargo 1.60.0-nightly (c082648 2022-02-08)
➜ mold --version
mold 1.0.3 (a7333bdb4e50f9fcde443fd8cefea5afb1364f52; compatible with GNU ld)
```

Please let me know if you need any additional information to help diagnose this.
