### ISSUE TITLE
Cross-compiling from M1 Mac to x86_64 Linux failed only in Rust project

### ISSUE THREAD

**Issue by inflation** [rui314/mold#564]
Hi, I'm trying to cross compile the default hello world Rust program to x86_64, with the config:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=/opt/homebrew/bin/ld.mold",
  "-Clink-arg=--sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot"]
```
But if failed with:
```
mold: fatal: unknown command line option: -dynamic
```

Building command:
```bash
cargo build --target=x86_64-unknown-linux-gnu
```
Linking command:
```bash
 "cc" "-m64"
 ...
"-Wl,--as-needed" 
"-L" "/private/tmp/testing/target/x86_64-unknown-linux-gnu/debug/deps"
"-L" "/private/tmp/testing/target/debug/deps" 
"-L" "/Users/inflation/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
"-Wl,--start-group" "-Wl,-Bstatic" 
...
"-Wl,--end-group" 
"/Users/inflation/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-377835cfab8dae0d.rlib" 
"-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" 
"-L" "/Users/inflation/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
"-o" "/private/tmp/testing/target/x86_64-unknown-linux-gnu/debug/deps/testing-c379b9730434cd22" 
"-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" 
"-fuse-ld=/opt/homebrew/bin/ld.mold" "--sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot"
```

Furthermore, I tried to cross-compile a simple hello world in C with clang:
```
clang -target x86_64-unknown-linux-gnu --sysroot=/Volumes/CSP/x-tools/x86_64-unknown-linux-gnu/sysroot -fuse-ld=/opt/homebrew/bin/ld.mold test.c
```
It works without any problem. And I verified that it's a working x86_64 Linux program.

Could be a `cargo` issue though, maybe somewhere `-dynamic` is implicitly added?

**Comment by rui314** [comment]
Can you try to cross compile the default hello world without mold? Does it work?

**Comment by inflation** [comment]
It works if I use `x86_64-unknown-linux-gnu-gcc` as the linker.

**Comment by inflation** [comment]
It will invoke the system linker `ld`, which doesn't support cross-compiling.

```bash
ld: unknown option: --as-needed
```

**Comment by inflation** [comment]
I got some time to investigate more. So using `gcc` as the linker works fine (with a little hack):
```bash
ln -s /opt/homebrew/bin/ld.mold /Volumes/CSP/x-tools/aarch64-linux-gnu/aarch64-linux-gnu/bin/ld
```

```toml
[target.aarch64-unknown-linux-gnu]
linker = "/Volumes/CSP/x-tools/aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc"
```

But using `clang` with `aarch64-linux-gnu-ld` failed with the same issue. I guess I'd open an issue in the `cargo` repo to shed some light from their side.
